#ifndef ANARCHY_DEVICE_FORWARD_H
#define ANARCHY_DEVICE_FORWARD_H

struct anarchy_device;

/* Device state */
enum anarchy_device_state {
    ANARCHY_DEVICE_STATE_UNINITIALIZED = 0,
    ANARCHY_DEVICE_STATE_INITIALIZING,
    ANARCHY_DEVICE_STATE_READY,
    ANARCHY_DEVICE_STATE_ERROR,
    ANARCHY_DEVICE_STATE_DISCONNECTED
};

/* Device flags */
#define ANARCHY_DEVICE_FLAG_INITIALIZED   (1 << 0)
#define ANARCHY_DEVICE_FLAG_CONNECTED     (1 << 1)
#define ANARCHY_DEVICE_FLAG_ERROR         (1 << 2)
#define ANARCHY_DEVICE_FLAG_SUSPENDED     (1 << 3)

#endif /* ANARCHY_DEVICE_FORWARD_H */ 